support jest 28
tylergould/handlebars-jest pull request #29
Opened 2022-05-02 17:48 UTC by dcavanagh

2022-07-06 12:51 UTC, lorenzorad approved these changes
it should be released as a breaking change aka major semver release, right?

2022-07-06 13:07 UTC, lorenzorad commented
@scitech @miikaah do you have permissions to accept and merge this branch?

2022-07-06 13:29 UTC, scitech requested changes
Thanks for the PR. Would you mind removing package-lock, so we don't have two lockfiles in the project?

2022-07-11 14:55 UTC, scitech approved these changes

2022-07-11 14:56 UTC, merged